branches:
  only:
    - /^v.*$/
env:
  - RUST_SKIA_TAG="0.33.0" CXX="clang-6.0" CPLUS_INCLUDE_PATH="/usr/include/clang/6.0.1/include"
os:
  # - osx
  - linux
  # - windows
dist: trusty
language: node_js
node_js:
  - 12
cache:
  - cargo
  - npm
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - gcc-6
      - g++-6
# matrix:
#     include:
#       - os: linux
#         env: 
#           - RUST_SKIA_TAG="0.33.0"
#           - CXX="clang-6.0"
#           - CXXFLAGS="-stdlib=libc++"
#         addons:
#           apt:
#             sources:
#               - llvm-toolchain-trusty-6.0
#             packages:
#               - clang-6.0
before_install:
  # setup glic 2.17
  # - wget http://ftp.gnu.org/gnu/glibc/glibc-2.17.tar.gz
  # - tar -xvf glibc-2.17.tar.gz && mkdir glic-build-2.17
  # - cd glic-build-2.17 && ../glibc-2.17/configure --prefix=/usr --disable-profile --enable-add-ons --with-headers=/usr/include --with-binutils=/usr/bin && make && make install
  # - ll /lib64/libc*
  - sudo apt-get -y install libc6=2.17
  - ll /lib64/libc*
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export RUSTUP_OPTIONS="--default-host x86_64-pc-windows-msvc --default-toolchain stable-x86_64-pc-windows-msvc"; fi
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - export PATH="/usr/local/bin:$PATH"
  - echo $PATH
  - source "$HOME/.cargo/env" || true
  - ldd --version
  - rustc --version
  - cargo --version
  - node -v
  - npm -v
  # Setup clang/llvm
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - sudo ln -s /usr/bin/clang-6.0 /usr/local/bin/clang
  - sudo ln -s /usr/bin/clang-6.0 /usr/local/bin/clang++
  - sudo ln -s /usr/bin/clang-6.0 /usr/local/bin/c++
  - gcc -v && g++ -v
  - c++ -v && clang -v && clang++ -v
  # Clone the rust-skia repo with the proper tag
  - git clone --depth 1 --branch $RUST_SKIA_TAG https://github.com/rust-skia/rust-skia.git ../rust-skia
  - npm install -g neon-cli
  # Build rust-skia from source on linux (use downloaded binaries on mac)
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then sed -i.bak 's/^skia-safe.*/skia-safe = { path = "..\/..\/rust-skia\/skia-safe", features = ["textlayout"] }/' native/Cargo.toml; fi
install:
  - travis_wait 25 npm ci
script:
  - npm test
  - npm run package
  - if [ -n "$TRAVIS_TAG" ]; then npm run upload-binary || exit 0; fi
